"""Shared fixtures for the Playwright UI test suite.

These tests run against a *live* MyPi process (uvicorn subprocess) and
a real Postgres. They're invoked via `pytest tests/playwright -m playwright`
and excluded from the default `pytest` run by the marker filter in
pytest.ini, so the unit/integration suite stays fast.

Architecture:
  - Session fixture `live_app` runs alembic, spawns uvicorn in a subprocess,
    waits for /api/health to return 200, and tears the process down at exit.
  - Function fixture `db_reset` truncates stats/queries/sites/instances and
    rewinds the admin user back to its bootstrap state between tests.
  - Function fixture `seed_data` inserts a realistic site + instance + 24h
    of stats snapshots + a few hundred query logs so the dashboard renders
    real-looking content.
  - Function fixture `logged_in_page` walks the login + forced-password-
    change flow once and hands the test a Playwright `Page` ready to use.

Required env vars (set by the ui-tests workflow; can be set locally):
  DATABASE_URL              PostgreSQL DSN reachable from the test process
                            *and* from the uvicorn subprocess.
  SECRET_KEY                Any non-empty string; defaulted here if missing.
  ENCRYPTION_KEY            Optional — auto-generated by the app on first run.
  MYPI_SKIP_TESTCONTAINER   Must be "1" so the parent tests/conftest.py
                            doesn't try to spin its own Postgres container.
"""
from __future__ import annotations

import os
import socket
import subprocess
import sys
import time
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterator

import httpx
import pytest


def pytest_collection_modifyitems(config, items):
    """Auto-tag every test in this directory with the `playwright` marker.

    `pytestmark = pytest.mark.playwright` at module level *does not*
    propagate from a conftest.py to tests in the same directory — only
    the collection hook does. Without this, the default `pytest` run
    (configured with `-m "not playwright"` in pytest.ini) collects the
    UI tests and trips on `alembic upgrade head` because there's no
    Postgres in the fast suite's environment.
    """
    rootpath = Path(__file__).parent.resolve()
    for item in items:
        try:
            item_path = Path(str(item.path)).resolve()
        except Exception:
            continue
        if rootpath in item_path.parents or item_path == rootpath:
            item.add_marker(pytest.mark.playwright)


# ── Constants ────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
TEST_YAML = Path(__file__).parent / "pihole_instances.test.yml"

# Bootstrap admin password. Must match what the live_app fixture passes
# via INITIAL_ADMIN_PASSWORD so logged_in_page knows how to log in.
ADMIN_USERNAME = "admin"
ADMIN_BOOTSTRAP_PASSWORD = "ui-test-bootstrap-pw-123"
ADMIN_NEW_PASSWORD = "ui-test-rotated-pw-456"


# ── Helpers ──────────────────────────────────────────────────────────────────


def _free_port() -> int:
    """Reserve a free TCP port by binding ephemerally and releasing it.

    Race-prone in theory, fine in practice for a single-test-process run.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _wait_for_health(url: str, timeout: float = 30.0) -> None:
    deadline = time.monotonic() + timeout
    last_err: Exception | None = None
    while time.monotonic() < deadline:
        try:
            r = httpx.get(f"{url}/api/health", timeout=2.0)
            if r.status_code == 200:
                return
        except Exception as exc:
            last_err = exc
        time.sleep(0.3)
    raise RuntimeError(
        f"Live MyPi did not become healthy within {timeout}s "
        f"(last error: {last_err})"
    )


# ── Session: bring up the app ────────────────────────────────────────────────


@pytest.fixture(scope="session")
def live_app() -> Iterator[str]:
    """Start uvicorn in a subprocess and yield its base URL.

    Runs `alembic upgrade head` first so the schema is in place. The DB
    URL must already point at a reachable Postgres — the test driver and
    the app subprocess both connect to the same database.
    """
    if "DATABASE_URL" not in os.environ:
        pytest.skip("DATABASE_URL not set — skipping Playwright suite.")

    env = os.environ.copy()
    # Required app config. Bootstrap password is fixed so logged_in_page
    # can log in without scraping container logs.
    env.setdefault("SECRET_KEY", "ui-test-secret-key-not-for-production")
    env["INITIAL_ADMIN_USER"] = ADMIN_USERNAME
    env["INITIAL_ADMIN_PASSWORD"] = ADMIN_BOOTSTRAP_PASSWORD
    env["PIHOLE_CONFIG_PATH"] = str(TEST_YAML)
    env["ENABLE_API_DOCS"] = "true"  # /docs is exercised by test_navigation
    # Push the polling intervals out so the scheduler never fires during a
    # test run — without real Pi-holes the polls would just log errors.
    env["STATS_POLL_INTERVAL"] = "999999"
    env["QUERIES_POLL_INTERVAL"] = "999999"
    env.setdefault("DATA_RETENTION_DAYS", "999999")
    # Don't ever collide with the parent suite's testcontainer logic.
    env["MYPI_SKIP_TESTCONTAINER"] = "1"

    # Apply migrations against the same DB the subprocess will use.
    # Alembic env.py reads DATABASE_URL out of app.config, which uses
    # asyncpg. For the migration step we swap the driver to psycopg
    # because alembic runs synchronously.
    sync_db_url = env["DATABASE_URL"].replace(
        "postgresql+asyncpg://", "postgresql+psycopg://",
    )
    migrate_env = env.copy()
    migrate_env["DATABASE_URL"] = sync_db_url
    subprocess.run(
        ["alembic", "upgrade", "head"],
        cwd=REPO_ROOT, env=migrate_env, check=True,
    )

    port = _free_port()
    base_url = f"http://127.0.0.1:{port}"

    # Capture stdout/stderr to a log file so failures are diagnosable
    # from CI artifacts without piping through pytest's capture machinery.
    log_path = REPO_ROOT / "playwright-app.log"
    log_fh = open(log_path, "w")
    proc = subprocess.Popen(
        [
            sys.executable, "-m", "uvicorn", "app.main:app",
            "--host", "127.0.0.1", "--port", str(port),
            "--log-level", "info",
        ],
        cwd=REPO_ROOT, env=env, stdout=log_fh, stderr=subprocess.STDOUT,
    )

    try:
        _wait_for_health(base_url)
        yield base_url
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=5)
        log_fh.close()


# ── Sync DB session for seeding / cleanup ──────────────────────────────────
#
# Everything below runs synchronously via psycopg. The Playwright sync
# API spins up its own event loop internally (`SyncBase.dispatcher_fiber`)
# and pytest-asyncio spins up another for async fixtures — mixing the two
# from inside one test reliably trips
# "RuntimeError: Cannot run the event loop while another loop is running."
# Sidestepping the conflict by going pure-sync for fixture work is far
# simpler than trying to reconcile the two loops.


@pytest.fixture(scope="session")
def db_engine(live_app):
    """Sync SQLAlchemy engine pointed at the test database.

    Driver swap: app uses asyncpg in prod; tests use psycopg here so the
    engine is plain-sync. Both target the same Postgres.
    """
    from sqlalchemy import create_engine

    sync_url = os.environ["DATABASE_URL"].replace(
        "postgresql+asyncpg://", "postgresql+psycopg://",
    )
    return create_engine(sync_url, future=True)


def _truncate_data(db_engine) -> None:
    """Clear stats/queries/instances/sites — but leave users + app_settings.

    Used as the inner step shared between `db_reset` (which also rewinds
    the admin user) and `db_reset_data` (which leaves users alone so
    a cached session cookie keeps working).
    """
    from sqlalchemy import text

    with db_engine.begin() as conn:
        # Order matters: child rows before parents because of FKs.
        conn.execute(text("TRUNCATE query_logs CASCADE"))
        conn.execute(text("TRUNCATE stats_snapshots CASCADE"))
        conn.execute(text("TRUNCATE pihole_instances CASCADE"))
        conn.execute(text("TRUNCATE site_settings CASCADE"))
        conn.execute(text("TRUNCATE sites CASCADE"))
        # api_keys + revoked_tokens accumulate in tests that exercise
        # the API-key UI / logout flow; clear them so duplicate-name
        # creates don't fail across tests.
        conn.execute(text("TRUNCATE api_keys CASCADE"))
        conn.execute(text("TRUNCATE revoked_tokens CASCADE"))


@pytest.fixture
def db_reset(db_engine):
    """Truncate test data + rewind admin to bootstrap state.

    Used by tests that exercise the login / forced-password-change flow,
    where every test must start from "fresh login required, password
    change forced." `app_settings` is preserved because it stores the
    auto-generated ENCRYPTION_KEY; nuking it would break instance
    encryption mid-run.
    """
    from sqlalchemy import text

    from app.auth import hash_password

    bootstrap_hash = hash_password(ADMIN_BOOTSTRAP_PASSWORD)

    _truncate_data(db_engine)
    with db_engine.begin() as conn:
        conn.execute(
            text(
                "UPDATE users SET hashed_password = :h, "
                "password_change_required = TRUE WHERE username = :u"
            ),
            {"h": bootstrap_hash, "u": ADMIN_USERNAME},
        )


@pytest.fixture
def db_reset_data(db_engine):
    """Truncate test data only — leave users untouched.

    Used by `authed_page` so the session-scoped storage_state cookie
    keeps validating. The fixture also forces the admin into
    "fully-logged-in" state (password rotated, change-required cleared)
    so a previous auth-flow test that left the bootstrap state behind
    doesn't trip the `/change-password` redirect mid-session.
    """
    from sqlalchemy import text

    from app.auth import hash_password

    new_pw_hash = hash_password(ADMIN_NEW_PASSWORD)

    _truncate_data(db_engine)
    with db_engine.begin() as conn:
        conn.execute(
            text(
                "UPDATE users SET hashed_password = :h, "
                "password_change_required = FALSE WHERE username = :u"
            ),
            {"h": new_pw_hash, "u": ADMIN_USERNAME},
        )


@pytest.fixture
def seed_data(db_engine, db_reset_data):
    """Seed a realistic site + instance + 24h of stats + 200 queries.

    Returns a dict with the IDs the test can reference. Depends on
    `db_reset_data` (not `db_reset`) so it composes cleanly with
    `authed_page` — that fixture's session-scoped storage_state cookie
    requires the admin to stay in "fully-logged-in" state.
    """
    from sqlalchemy import text

    site_id = uuid.uuid4()
    instance_id = uuid.uuid4()
    now = datetime.now(timezone.utc)

    with db_engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO sites (id, name, slug, is_main, is_active, sort_order) "
                "VALUES (:id, :name, :slug, TRUE, TRUE, 0)"
            ),
            {"id": site_id, "name": "UI Test Site", "slug": "ui-test"},
        )
        conn.execute(
            text(
                "INSERT INTO pihole_instances "
                "(id, site_id, name, url, api_password, color, is_active, "
                " is_master, last_seen_at, version_core, version_ftl, version_web) "
                "VALUES (:id, :site_id, :name, :url, '', :color, TRUE, TRUE, "
                "        :seen, 'v6.0.0', 'v6.0.0', 'v6.0.0')"
            ),
            {
                "id": instance_id, "site_id": site_id,
                "name": "Test-Pihole-1", "url": "http://test-pihole.invalid",
                "color": "#00a65a", "seen": now,
            },
        )

        # 25 hourly stats snapshots — strictly increasing totals so the
        # latest snapshot's `domains_on_blocklist` lands on the dashboard.
        snapshots = []
        for hours_ago in range(24, -1, -1):
            ts = now - timedelta(hours=hours_ago)
            total = 1000 * (24 - hours_ago) + 250
            blocked = total // 4
            snapshots.append({
                "id": uuid.uuid4(), "instance_id": instance_id,
                "collected_at": ts, "status": "online",
                "dns_queries_today": total, "queries_blocked": blocked,
                "percent_blocked": round(blocked / total * 100, 2),
                "domains_on_blocklist": 125000,
                "unique_clients": 12,
                "queries_cached": total // 5,
                "queries_forwarded": total - blocked - (total // 5),
            })
        conn.execute(
            text(
                "INSERT INTO stats_snapshots "
                "(id, instance_id, collected_at, status, dns_queries_today, "
                " queries_blocked, percent_blocked, domains_on_blocklist, "
                " unique_clients, queries_cached, queries_forwarded) VALUES "
                "(:id, :instance_id, :collected_at, :status, :dns_queries_today, "
                " :queries_blocked, :percent_blocked, :domains_on_blocklist, "
                " :unique_clients, :queries_cached, :queries_forwarded)"
            ),
            snapshots,
        )

        # 200 query logs spread across the last hour, mix of allowed/blocked.
        domains = [
            "ads.example.com", "tracker.example.net", "analytics.example.org",
            "cdn.example.com", "api.example.io", "static.example.dev",
        ]
        clients = ["192.168.1.10", "192.168.1.20", "192.168.1.30"]
        rows = []
        for i in range(200):
            ts = now - timedelta(seconds=i * 18)
            blocked = i % 4 == 0
            rows.append({
                "id": uuid.uuid4(), "instance_id": instance_id,
                "pihole_query_id": str(i),
                "timestamp": ts,
                "client_ip": clients[i % len(clients)],
                "client_name": None,
                "query_type": "A",
                "domain": domains[i % len(domains)],
                # GRAVITY is in app.api.stats.BLOCKED_STATUSES; "BLOCKED"
                # is not — using the wrong literal would silently zero
                # the dashboard's blocked-counts assertion.
                "status": "GRAVITY" if blocked else "FORWARDED",
                "reply_type": "NXDOMAIN" if blocked else "IP",
                "reply_time_ms": 1.2 if blocked else 18.7,
            })
        conn.execute(
            text(
                "INSERT INTO query_logs "
                "(id, instance_id, pihole_query_id, timestamp, client_ip, "
                " client_name, query_type, domain, status, reply_type, "
                " reply_time_ms) VALUES "
                "(:id, :instance_id, :pihole_query_id, :timestamp, :client_ip, "
                " :client_name, :query_type, :domain, :status, :reply_type, "
                " :reply_time_ms)"
            ),
            rows,
        )

    return {
        "site_id": str(site_id), "site_slug": "ui-test",
        "instance_id": str(instance_id), "instance_name": "Test-Pihole-1",
    }


# ── Playwright glue ──────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def base_url(live_app) -> str:
    """Override pytest-playwright's `base_url` so `page.goto('/')` works."""
    return live_app


@pytest.fixture
def with_main_site(db_engine, db_reset_data):
    """Insert a Default Main site after db_reset_data wipes the table.

    Several settings routes (sync_schedule, poll_settings, pushover) write
    to `site_settings` keyed on the active Main site — without one the
    save handler raises and the UI shows "Failed to save", which makes
    those tests look like UI bugs when they're really test-fixture bugs.

    The test YAML is empty (`sites: []`) so the app's startup
    `sync_sites_and_instances` doesn't create a Main either. This
    fixture fills the gap for tests that need to exercise per-site
    settings end-to-end.
    """
    from sqlalchemy import text

    site_id = uuid.uuid4()
    with db_engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO sites (id, name, slug, is_main, is_active, sort_order) "
                "VALUES (:id, 'Default', 'default', TRUE, TRUE, 0)"
            ),
            {"id": site_id},
        )
    return str(site_id)


@pytest.fixture
def logged_in_page(page, base_url, db_reset):
    """A Playwright page that has completed login + forced password change.

    Used by tests that need to exercise the full auth flow on each call
    (e.g. test_full_login_then_logout). Tests that just need an
    authenticated session to reach internal pages should use the
    cheaper `authed_page` fixture, which reuses cookies across tests
    and keeps total /login hits well under SlowAPI's 10/min limit.
    """
    page.goto(f"{base_url}/login")
    page.fill("#username", ADMIN_USERNAME)
    page.fill("#password", ADMIN_BOOTSTRAP_PASSWORD)
    page.click("button[type=submit]")
    page.wait_for_url("**/change-password")

    page.fill("#current_password", ADMIN_BOOTSTRAP_PASSWORD)
    page.fill("#new_password", ADMIN_NEW_PASSWORD)
    page.fill("#confirm_password", ADMIN_NEW_PASSWORD)
    page.click("button[type=submit]")
    page.wait_for_url(f"{base_url}/")
    return page


@pytest.fixture(scope="session")
def _auth_storage_state(live_app, browser, db_engine):
    """Log in once at session scope; capture the cookie state.

    The /login route is rate-limited to 10 requests/minute by SlowAPI.
    With ~12 tests using `logged_in_page`, the per-test login pattern
    consistently hit 429 toward the end of the suite. Caching the
    authenticated cookie state once and replaying it via Playwright's
    `storage_state` keeps the suite under that limit (5 logins from
    auth-flow tests + 1 here = 6 total).
    """
    from sqlalchemy import text

    from app.auth import hash_password

    # Force admin into bootstrap state so the login + change-password
    # flow we walk below is deterministic regardless of whatever shape
    # the DB happens to be in when the session starts.
    bootstrap_hash = hash_password(ADMIN_BOOTSTRAP_PASSWORD)
    with db_engine.begin() as conn:
        conn.execute(
            text(
                "UPDATE users SET hashed_password = :h, "
                "password_change_required = TRUE WHERE username = :u"
            ),
            {"h": bootstrap_hash, "u": ADMIN_USERNAME},
        )

    context = browser.new_context()
    page = context.new_page()
    try:
        page.goto(f"{live_app}/login")
        page.fill("#username", ADMIN_USERNAME)
        page.fill("#password", ADMIN_BOOTSTRAP_PASSWORD)
        page.click("button[type=submit]")
        page.wait_for_url("**/change-password")

        page.fill("#current_password", ADMIN_BOOTSTRAP_PASSWORD)
        page.fill("#new_password", ADMIN_NEW_PASSWORD)
        page.fill("#confirm_password", ADMIN_NEW_PASSWORD)
        page.click("button[type=submit]")
        page.wait_for_url(f"{live_app}/")

        return context.storage_state()
    finally:
        context.close()


@pytest.fixture
def authed_page(live_app, browser, _auth_storage_state, db_reset_data):
    """Authenticated page using the session-scoped storage state.

    Per-test cost is a fresh browser context (~50 ms) plus replaying
    the cached cookies — no /login round-trip, so we don't burn the
    rate-limit bucket. `db_reset_data` runs before this so the
    dashboard starts each test on a clean slate.
    """
    context = browser.new_context(storage_state=_auth_storage_state)
    page = context.new_page()
    try:
        page.goto(f"{live_app}/")
        yield page
    finally:
        context.close()
