"""Shared fixtures for the Playwright UI test suite.

These tests run against a *live* MyPi process (uvicorn subprocess) and
a real Postgres. They're invoked via `pytest tests/playwright -m playwright`
and excluded from the default `pytest` run by the marker filter in
pytest.ini, so the unit/integration suite stays fast.

Architecture:
  - Session fixture `live_app` runs alembic, spawns uvicorn in a subprocess,
    waits for /api/health to return 200, and tears the process down at exit.
  - Function fixture `db_reset` truncates stats/queries/sites/instances and
    rewinds the admin user back to its bootstrap state between tests.
  - Function fixture `seed_data` inserts a realistic site + instance + 24h
    of stats snapshots + a few hundred query logs so the dashboard renders
    real-looking content.
  - Function fixture `logged_in_page` walks the login + forced-password-
    change flow once and hands the test a Playwright `Page` ready to use.

Required env vars (set by the ui-tests workflow; can be set locally):
  DATABASE_URL              PostgreSQL DSN reachable from the test process
                            *and* from the uvicorn subprocess.
  SECRET_KEY                Any non-empty string; defaulted here if missing.
  ENCRYPTION_KEY            Optional — auto-generated by the app on first run.
  MYPI_SKIP_TESTCONTAINER   Must be "1" so the parent tests/conftest.py
                            doesn't try to spin its own Postgres container.
"""
from __future__ import annotations

import os
import socket
import subprocess
import sys
import time
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterator

import httpx
import pytest


def pytest_collection_modifyitems(config, items):
    """Auto-tag every test in this directory with the `playwright` marker.

    `pytestmark = pytest.mark.playwright` at module level *does not*
    propagate from a conftest.py to tests in the same directory — only
    the collection hook does. Without this, the default `pytest` run
    (configured with `-m "not playwright"` in pytest.ini) collects the
    UI tests and trips on `alembic upgrade head` because there's no
    Postgres in the fast suite's environment.
    """
    rootpath = Path(__file__).parent.resolve()
    for item in items:
        try:
            item_path = Path(str(item.path)).resolve()
        except Exception:
            continue
        if rootpath in item_path.parents or item_path == rootpath:
            item.add_marker(pytest.mark.playwright)


# ── Constants ────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
TEST_YAML = Path(__file__).parent / "pihole_instances.test.yml"

# Bootstrap admin password. Must match what the live_app fixture passes
# via INITIAL_ADMIN_PASSWORD so logged_in_page knows how to log in.
ADMIN_USERNAME = "admin"
ADMIN_BOOTSTRAP_PASSWORD = "ui-test-bootstrap-pw-123"
ADMIN_NEW_PASSWORD = "ui-test-rotated-pw-456"


# ── Helpers ──────────────────────────────────────────────────────────────────


def _free_port() -> int:
    """Reserve a free TCP port by binding ephemerally and releasing it.

    Race-prone in theory, fine in practice for a single-test-process run.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _wait_for_health(url: str, timeout: float = 30.0) -> None:
    deadline = time.monotonic() + timeout
    last_err: Exception | None = None
    while time.monotonic() < deadline:
        try:
            r = httpx.get(f"{url}/api/health", timeout=2.0)
            if r.status_code == 200:
                return
        except Exception as exc:
            last_err = exc
        time.sleep(0.3)
    raise RuntimeError(
        f"Live MyPi did not become healthy within {timeout}s "
        f"(last error: {last_err})"
    )


# ── Session: bring up the app ────────────────────────────────────────────────


@pytest.fixture(scope="session")
def live_app() -> Iterator[str]:
    """Start uvicorn in a subprocess and yield its base URL.

    Runs `alembic upgrade head` first so the schema is in place. The DB
    URL must already point at a reachable Postgres — the test driver and
    the app subprocess both connect to the same database.
    """
    if "DATABASE_URL" not in os.environ:
        pytest.skip("DATABASE_URL not set — skipping Playwright suite.")

    env = os.environ.copy()
    # Required app config. Bootstrap password is fixed so logged_in_page
    # can log in without scraping container logs.
    env.setdefault("SECRET_KEY", "ui-test-secret-key-not-for-production")
    env["INITIAL_ADMIN_USER"] = ADMIN_USERNAME
    env["INITIAL_ADMIN_PASSWORD"] = ADMIN_BOOTSTRAP_PASSWORD
    env["PIHOLE_CONFIG_PATH"] = str(TEST_YAML)
    env["ENABLE_API_DOCS"] = "true"  # /docs is exercised by test_navigation
    # Push the polling intervals out so the scheduler never fires during a
    # test run — without real Pi-holes the polls would just log errors.
    env["STATS_POLL_INTERVAL"] = "999999"
    env["QUERIES_POLL_INTERVAL"] = "999999"
    env.setdefault("DATA_RETENTION_DAYS", "999999")
    # Don't ever collide with the parent suite's testcontainer logic.
    env["MYPI_SKIP_TESTCONTAINER"] = "1"

    # Apply migrations against the same DB the subprocess will use.
    # Alembic env.py reads DATABASE_URL out of app.config, which uses
    # asyncpg. For the migration step we swap the driver to psycopg
    # because alembic runs synchronously.
    sync_db_url = env["DATABASE_URL"].replace(
        "postgresql+asyncpg://", "postgresql+psycopg://",
    )
    migrate_env = env.copy()
    migrate_env["DATABASE_URL"] = sync_db_url
    subprocess.run(
        ["alembic", "upgrade", "head"],
        cwd=REPO_ROOT, env=migrate_env, check=True,
    )

    port = _free_port()
    base_url = f"http://127.0.0.1:{port}"

    # Capture stdout/stderr to a log file so failures are diagnosable
    # from CI artifacts without piping through pytest's capture machinery.
    log_path = REPO_ROOT / "playwright-app.log"
    log_fh = open(log_path, "w")
    proc = subprocess.Popen(
        [
            sys.executable, "-m", "uvicorn", "app.main:app",
            "--host", "127.0.0.1", "--port", str(port),
            "--log-level", "info",
        ],
        cwd=REPO_ROOT, env=env, stdout=log_fh, stderr=subprocess.STDOUT,
    )

    try:
        _wait_for_health(base_url)
        yield base_url
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=5)
        log_fh.close()


# ── Async DB session for seeding / cleanup ──────────────────────────────────


@pytest.fixture(scope="session")
def db_engine(live_app):
    """Async SQLAlchemy engine pointed at the test database.

    Imported lazily so the parent tests/conftest.py has had a chance to
    set DATABASE_URL before SQLAlchemy reads it.
    """
    from sqlalchemy.ext.asyncio import create_async_engine

    return create_async_engine(os.environ["DATABASE_URL"], future=True)


@pytest.fixture
async def db_reset(db_engine):
    """Truncate test data + reset admin user before each test.

    Runs *before* the test body. We clear: stats_snapshots, query_logs,
    pihole_instances, sites — and rewind the admin's bootstrap state so
    every test starts from "fresh login required, password change forced."

    `app_settings` is preserved because it stores the auto-generated
    ENCRYPTION_KEY; nuking it would break instance encryption mid-run.
    """
    from sqlalchemy import text

    from app.auth import hash_password

    bootstrap_hash = hash_password(ADMIN_BOOTSTRAP_PASSWORD)

    async with db_engine.begin() as conn:
        # Order matters: child rows before parents because of FKs.
        await conn.execute(text("TRUNCATE query_logs CASCADE"))
        await conn.execute(text("TRUNCATE stats_snapshots CASCADE"))
        await conn.execute(text("TRUNCATE pihole_instances CASCADE"))
        await conn.execute(text("TRUNCATE site_settings CASCADE"))
        await conn.execute(text("TRUNCATE sites CASCADE"))
        await conn.execute(
            text(
                "UPDATE users SET hashed_password = :h, "
                "password_change_required = TRUE WHERE username = :u"
            ),
            {"h": bootstrap_hash, "u": ADMIN_USERNAME},
        )
    yield


@pytest.fixture
async def seed_data(db_engine, db_reset):
    """Seed a realistic site + instance + 24h of stats + 200 queries.

    Returns a dict with the IDs the test can reference. Inserts run after
    `db_reset` so the previous test's seed has already been wiped.
    """
    from sqlalchemy import text

    site_id = uuid.uuid4()
    instance_id = uuid.uuid4()
    now = datetime.now(timezone.utc)

    async with db_engine.begin() as conn:
        await conn.execute(
            text(
                "INSERT INTO sites (id, name, slug, is_main, is_active, sort_order) "
                "VALUES (:id, :name, :slug, TRUE, TRUE, 0)"
            ),
            {"id": site_id, "name": "UI Test Site", "slug": "ui-test"},
        )
        await conn.execute(
            text(
                "INSERT INTO pihole_instances "
                "(id, site_id, name, url, api_password, color, is_active, "
                " is_master, last_seen_at, version_core, version_ftl, version_web) "
                "VALUES (:id, :site_id, :name, :url, '', :color, TRUE, TRUE, "
                "        :seen, 'v6.0.0', 'v6.0.0', 'v6.0.0')"
            ),
            {
                "id": instance_id, "site_id": site_id,
                "name": "Test-Pihole-1", "url": "http://test-pihole.invalid",
                "color": "#00a65a", "seen": now,
            },
        )

        # 24 hourly stats snapshots — strictly increasing totals so the
        # dashboard "Total Queries" card has something interesting to render.
        snapshots = []
        for hours_ago in range(24, -1, -1):
            ts = now - timedelta(hours=hours_ago)
            total = 1000 * (24 - hours_ago) + 250
            blocked = total // 4
            snapshots.append({
                "id": uuid.uuid4(), "instance_id": instance_id,
                "collected_at": ts, "status": "online",
                "dns_queries_today": total, "queries_blocked": blocked,
                "percent_blocked": round(blocked / total * 100, 2),
                "domains_on_blocklist": 125000,
                "unique_clients": 12,
                "queries_cached": total // 5,
                "queries_forwarded": total - blocked - (total // 5),
            })
        await conn.execute(
            text(
                "INSERT INTO stats_snapshots "
                "(id, instance_id, collected_at, status, dns_queries_today, "
                " queries_blocked, percent_blocked, domains_on_blocklist, "
                " unique_clients, queries_cached, queries_forwarded) VALUES "
                "(:id, :instance_id, :collected_at, :status, :dns_queries_today, "
                " :queries_blocked, :percent_blocked, :domains_on_blocklist, "
                " :unique_clients, :queries_cached, :queries_forwarded)"
            ),
            snapshots,
        )

        # 200 query logs spread across the last hour, mix of allowed/blocked.
        domains = [
            "ads.example.com", "tracker.example.net", "analytics.example.org",
            "cdn.example.com", "api.example.io", "static.example.dev",
        ]
        clients = ["192.168.1.10", "192.168.1.20", "192.168.1.30"]
        rows = []
        for i in range(200):
            ts = now - timedelta(seconds=i * 18)
            blocked = i % 4 == 0
            rows.append({
                "id": uuid.uuid4(), "instance_id": instance_id,
                "pihole_query_id": str(i),
                "timestamp": ts,
                "client_ip": clients[i % len(clients)],
                "client_name": None,
                "query_type": "A",
                "domain": domains[i % len(domains)],
                # GRAVITY is in app.api.stats.BLOCKED_STATUSES; "BLOCKED"
                # is not — using the wrong literal would silently zero
                # the dashboard's blocked-counts assertion.
                "status": "GRAVITY" if blocked else "FORWARDED",
                "reply_type": "NXDOMAIN" if blocked else "IP",
                "reply_time_ms": 1.2 if blocked else 18.7,
            })
        await conn.execute(
            text(
                "INSERT INTO query_logs "
                "(id, instance_id, pihole_query_id, timestamp, client_ip, "
                " client_name, query_type, domain, status, reply_type, "
                " reply_time_ms) VALUES "
                "(:id, :instance_id, :pihole_query_id, :timestamp, :client_ip, "
                " :client_name, :query_type, :domain, :status, :reply_type, "
                " :reply_time_ms)"
            ),
            rows,
        )

    return {
        "site_id": str(site_id), "site_slug": "ui-test",
        "instance_id": str(instance_id), "instance_name": "Test-Pihole-1",
    }


# ── Playwright glue ──────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def base_url(live_app) -> str:
    """Override pytest-playwright's `base_url` so `page.goto('/')` works."""
    return live_app


@pytest.fixture
def logged_in_page(page, base_url, db_reset):
    """A Playwright page that has completed login + forced password change.

    Each test starts from the bootstrap state (forced change required), so
    we run through both screens here and hand the test a fully authenticated
    session pointed at the dashboard.
    """
    page.goto(f"{base_url}/login")
    page.fill("#username", ADMIN_USERNAME)
    page.fill("#password", ADMIN_BOOTSTRAP_PASSWORD)
    page.click("button[type=submit]")
    page.wait_for_url("**/change-password")

    page.fill("#current_password", ADMIN_BOOTSTRAP_PASSWORD)
    page.fill("#new_password", ADMIN_NEW_PASSWORD)
    page.fill("#confirm_password", ADMIN_NEW_PASSWORD)
    page.click("button[type=submit]")
    page.wait_for_url(f"{base_url}/")
    return page
